manaelproxy/manael

- main.go
> Add support PNG

- main.go
> Content-Length

- main.go
> Support If-Modified-Since

- main.go
> Cache-Control

- main.go
> Revert "Fix pass-through"

- main.go
> Support image.Paletted

- main.go
> Support image.Gray

- main.go
> Support -bind argument

- Gopkg.lock
- Gopkg.toml
- main.go
> Introduce gorilla/handlers

- .gitignore
- Dockerfile
- README.md
> Rename to Manael

- cmd/manael/main.go
> Use multi processors

- example_test.go
- manael.go
> Add example

- .circleci/config.yml
> Introduce CircleCI

- manael_test.go
- request.go
> Add support for If-None-Match

- .circleci/config.yml
- README.md
- converter.go
- manael.go
> Remove dependency of libjpeg

- manael.go
- manael_test.go
> Disable Range requests

- request.go
- request_test.go
> Add support for X-Forwarded-For

- request.go
> Copy X-Forwarded-Proto

- manael.go
- manael_test.go
> Add support for Cache-Control: no-transform

- cmd/manael/main.go
> feat: adopt os environment

- cmd/manael/main.go
- go.mod
- go.sum
> feat: logging handler

- manael.go
> feat: add server header

- .circleci/config.yml
- .gitignore
> chore(ci): add show cover

- CONTRIBUTING.md
> doc: add contributing.md

- .editorconfig
- .gitignore
- Makefile
> chore: add makefile

- .github/workflows/release.yml
Refs: 9e3a23b7792361fc83438096c056f7e33f64b5ad.
> revert: ci(github-actions): use env values (#296)

- transport.go
> feat(transprot): add flag for avif

- .github/workflows/release-please.yml
Reverts manaelproxy/manael#444
> revert(release-please): remove command

- .husky/commit-msg
- commitlint.config.js
- package.json
- yarn.lock
> ci(commitlint): introduce commitlint

- website/package.json
- yarn.lock
Reverts manaelproxy/manael#673
> revert(deps): downgrade react monorepo to v17

- package.json
- yarn.lock
Fix https://github.com/manaelproxy/manael/security/dependabot/1
Fix https://github.com/manaelproxy/manael/security/dependabot/2
> build(deps): add cheerio and trim to resolutions

- website/docs/1-installation.md
These changes make the English version of the docs less choppy and more readable for English speakers.
> docs: improve English version of documentation

- .devcontainer/Dockerfile
- .github/workflows/go.yml
- encode.go
- go.mod
- go.sum
> revert(deps): downgrade module github.com/harukasan/go-libwebp
